<a href="https://colab.research.google.com/github/ismael-almazan/Programaci-n-para-anal-tica-descriptiva-y-predictiva/blob/main/Descomposici%C3%B3n_de_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
from sympy import Matrix, pprint, S
import numpy as np
#Definir la matriz B

B = Matrix([
    [S('39/4'), S('9/2'), S('2')],
    [S('-1'),   S('3'),   S('-1')],
    [S('-1'),   S('2'),   S('9/2')]
])
print("Matriz B:")
pprint(B)

# Calcular descomposición LU
L, U, perm = B.LUdecomposition()

print("\nMatriz triangular inferior L:")
pprint(L)

print("\nMatriz triangular superior U:")
pprint(U)

print("\nPermutaciones:", perm)

#Reconstruye la matriz
print("\nReconstrucción B:")
pprint(L * U)

Matriz B:
⎡39/4  9/2   2 ⎤
⎢              ⎥
⎢ -1    3   -1 ⎥
⎢              ⎥
⎣ -1    2   9/2⎦

Matriz triangular inferior L:
⎡  1    0   0⎤
⎢            ⎥
⎢-4/39  1   0⎥
⎢            ⎥
⎢       32   ⎥
⎢-4/39  ──  1⎥
⎣       45   ⎦

Matriz triangular superior U:
⎡39/4  9/2   2  ⎤
⎢               ⎥
⎢      45   -31 ⎥
⎢ 0    ──   ────⎥
⎢      13    39 ⎥
⎢               ⎥
⎢           1423⎥
⎢ 0     0   ────⎥
⎣           270 ⎦

Permutaciones: []

Reconstrucción B:
⎡39/4  9/2   2 ⎤
⎢              ⎥
⎢ -1    3   -1 ⎥
⎢              ⎥
⎣ -1    2   9/2⎦


In [40]:
#Descomposcion QR de la matriz B
# Calcular la descomposición QR
Q, R = B.QRdecomposition()


print("MATRIZ Q :\n")
pprint(Q)

print("\nMATRIZ R:\n")
pprint(R)

# Verificación: Q * R = B
print("VERIFICACIÓN Q * R = B:\n")
verificacion = Q * R
pprint(verificacion)

MATRIZ Q :

⎡39⋅√1553   924⋅√42640721    4⋅√27457  ⎤
⎢────────   ─────────────    ────────  ⎥
⎢  1553       42640721        27457    ⎥
⎢                                      ⎥
⎢-4⋅√1553   5281⋅√42640721  -96⋅√27457 ⎥
⎢─────────  ──────────────  ───────────⎥
⎢  1553        42640721        27457   ⎥
⎢                                      ⎥
⎢-4⋅√1553   3728⋅√42640721  135⋅√27457 ⎥
⎢─────────  ──────────────  ────────── ⎥
⎣  1553        42640721       27457    ⎦

MATRIZ R:

⎡√1553  311⋅√1553     64⋅√1553    ⎤
⎢─────  ─────────     ────────    ⎥
⎢  4      3106          1553      ⎥
⎢                                 ⎥
⎢       √42640721  13343⋅√42640721⎥
⎢  0    ─────────  ───────────────⎥
⎢         1553        42640721    ⎥
⎢                                 ⎥
⎢                    1423⋅√27457  ⎥
⎢  0        0        ───────────  ⎥
⎣                       54914     ⎦
VERIFICACIÓN Q * R = B:

⎡39/4  9/2   2 ⎤
⎢              ⎥
⎢ -1    3   -1 ⎥
⎢              ⎥
⎣ -1    2   9/2⎦


In [57]:
#Descomposicion SVD de la matriz B
#Se define de nuevo la matriz y se calcula con Numpy ya que
#con Sympy tarda demaciado tiempo

B = np.array([
    [39/4, 9/2, 2],
    [-1,   3,   -1],
    [-1,   2,   9/2]
], dtype=np.float64)

U, S, V = np.linalg.svd(B)

print("\nMatriz U:\n", U)
print("\nVector S:\n", S)
print("\nMatriz V:\n", V)

#Reconstrucción de la matriz original B
print("\nReconstrucción B:\n", U @ np.diag(S) @ V)


Matriz U:
 [[-0.99603384  0.08891522  0.0032655 ]
 [-0.01797912 -0.16518782 -0.98609824]
 [-0.08713972 -0.98224593  0.16613128]]

Vector S:
 [10.95745655  4.99235661  3.25161828]

Matriz V:
 [[-0.87668257 -0.42987796 -0.21594585]
 [ 0.40348823 -0.41261813 -0.81666611]
 [ 0.26196359 -0.80308855  0.53518582]]

Reconstrucción B:
 [[ 9.75  4.5   2.  ]
 [-1.    3.   -1.  ]
 [-1.    2.    4.5 ]]
