<a href="https://colab.research.google.com/github/ismael-almazan/Programaci-n-para-anal-tica-descriptiva-y-predictiva/blob/main/Practica4_263177.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulación de matrices.

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

*   Suma ambas matrices.
*   Resta la segunda matriz de la primera.
*   Multiplica la primera matriz por 2.
*   Realiza una multiplicación matricial entre las dos matrices.








In [6]:
import numpy as np

#Crear las dos matrices
matriz1 = np.random.randint(1,10,(3,3))
matriz2 = np.random.randint(1,10,(3,3))
print("Matriz 1:\n",matriz1)
print("Matriz 1:\n",matriz2)

#Sumar ambas matrices
suma = matriz1 + matriz2
print("Suma:\n",suma)

#Restar la segunda matriz de la primera
resta = matriz1 - matriz2
print("Resta:\n",resta)

#Multiplicar la primera matriz por 2
multiplicacion = matriz1 * 2
print("Multiplicacion:\n",multiplicacion)

#Realiza una multiplicacion matricial entre las dos matrices
multiplicacionmatrices = np.dot(matriz1,matriz2)
print("Multiplicacion matricial:\n",multiplicacionmatrices)

Matriz 1:
 [[9 2 8]
 [8 8 1]
 [4 4 6]]
Matriz 1:
 [[1 2 8]
 [4 2 4]
 [5 1 1]]
Suma:
 [[10  4 16]
 [12 10  5]
 [ 9  5  7]]
Resta:
 [[ 8  0  0]
 [ 4  6 -3]
 [-1  3  5]]
Multiplicacion:
 [[18  4 16]
 [16 16  2]
 [ 8  8 12]]
Multiplicacion matricial:
 [[57 30 88]
 [45 33 97]
 [50 22 54]]
